### ISSUE TITLE
Getting Content-Length header of response, for allocating Vec::with_capacity before downloading

### ISSUE THREAD

**Issue by Boscop** [SonnyX/download-async#141]
Thanks for this crate, it's very useful :)
It would be nice if you could add a method to get the value of the `Content-Length` header of the response, for allocating  `Vec::with_capacity` with the size of the response. 
Currently it's only possible to read the headers after downloading finished.

**Comment by SonnyX** [comment]
Thanks for the interest of the crate.
I don't see a way to manipulate the API of the crate which would allow you to receive the headers, set the size of the `vec` beforehand and then return to downloading, in a way that makes sense.
Currently you could use/abuse the `Progress` trait, as when the `content-length` is set, the `set_file_size` function of that trait is called, in which you can do whatever you wish with that information, such as potentially manipulating the size of the `Vec` (albeit probably through the use of unsafe rust at this point).
Although it could have been a nice optimization to set the file-size beforehand using `with_capacity`, any service is not guaranteed to set the `content-length` header, rendering it useless in those cases.
